GEM_PRICES = [
    {"name": "Alexandrite", "price": 500, "weight": 0},
    {"name": "Amber", "price": 100, "weight": 0},
    {"name": "Amethyst", "price": 100, "weight": 0},
    {"name": "Aquamarine", "price": 500, "weight": 0},
    {"name": "Azurite", "price": 10, "weight": 0},
    {"name": "Banded Agate", "price": 10, "weight": 0},
    {"name": "Black Opal", "price": 1000, "weight": 0},
    {"name": "Black Pearl", "price": 500, "weight": 0},
    {"name": "Black Sapphire", "price": 5000, "weight": 0},
    {"name": "Bloodstone", "price": 50, "weight": 0},
    {"name": "Blue Quartz", "price": 10, "weight": 0},
    {"name": "Blue Sapphire", "price": 1000, "weight": 0},
    {"name": "Blue Spinel", "price": 500, "weight": 0},
    {"name": "Carnelian", "price": 50, "weight": 0},
    {"name": "Chalcedony", "price": 50, "weight": 0},
    {"name": "Chrysoberyl", "price": 100, "weight": 0},
    {"name": "Chrysoprase", "price": 50, "weight": 0},
    {"name": "Citrine", "price": 50, "weight": 0},
    {"name": "Coral", "price": 100, "weight": 0},
    {"name": "Diamond", "price": 5000, "weight": 0},
    {"name": "Emerald", "price": 1000, "weight": 0},
    {"name": "Eye Agate", "price": 10, "weight": 0},
    {"name": "Fire Opal", "price": 1000, "weight": 0},
    {"name": "Garnet", "price": 100, "weight": 0},
    {"name": "Hematite", "price": 10, "weight": 0},
    {"name": "Jacinth", "price": 5000, "weight": 0},
    {"name": "Jade", "price": 100, "weight": 0},
    {"name": "Jasper", "price": 50, "weight": 0},
    {"name": "Jet", "price": 100, "weight": 0},
    {"name": "Lapis Lazuli", "price": 10, "weight": 0},
    {"name": "Malachite", "price": 10, "weight": 0},
    {"name": "Moonstone", "price": 50, "weight": 0},
    {"name": "Moss Agate", "price": 10, "weight": 0},
    {"name": "Obsidian", "price": 10, "weight": 0},
    {"name": "Onyx", "price": 50, "weight": 0},
    {"name": "Opal", "price": 1000, "weight": 0},
    {"name": "Pearl", "price": 100, "weight": 0},
    {"name": "Peridot", "price": 500, "weight": 0},
    {"name": "Quartz", "price": 50, "weight": 0},
    {"name": "Rhodochrosite", "price": 10, "weight": 0},
    {"name": "Ruby", "price": 5000, "weight": 0},
    {"name": "Sardonyx", "price": 50, "weight": 0},
    {"name": "Spinel", "price": 100, "weight": 0},
    {"name": "Star Rose Quartz", "price": 50, "weight": 0},
    {"name": "Star Ruby", "price": 1000, "weight": 0},
    {"name": "Star Sapphire", "price": 1000, "weight": 0},
    {"name": "Tiger Eye", "price": 10, "weight": 0},
    {"name": "Topaz", "price": 500, "weight": 0},
    {"name": "Tourmaline", "price": 100, "weight": 0},
    {"name": "Turquoise", "price": 10, "weight": 0},
    {"name": "Yellow Sapphire", "price": 1000, "weight": 0},
    {"name": "Zircon", "price": 10, "weight": 0},
]

MIN_MODIFIER = 0.04
MAX_MODIFIER = 5

SIZE_BOUNDARIES = {
    "Skull-Sized": 10,
    "Fist-Sized": 8,
    "Billiard-Sized": 6,
    "Eyeball-Sized": 4,
    "Standard": 1,
    "Small": 0.1,
    "Tiny": 0.01,
}